// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUV4A4ah7jkeQ5HPv7co16GL_2R0aKc9k',
    appId: '1:1063136139964:web:4c9b12954aa0e5ce24ceb9',
    messagingSenderId: '1063136139964',
    projectId: 'intromobile2-a763d',
    authDomain: 'intromobile2-a763d.firebaseapp.com',
    storageBucket: 'intromobile2-a763d.firebasestorage.app',
    measurementId: 'G-BJEVXYF611',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI3H4PjwUCJgwnWi2EurfCyrhBmfkVnos',
    appId: '1:1063136139964:android:cd1c8f03d3498fbf24ceb9',
    messagingSenderId: '1063136139964',
    projectId: 'intromobile2-a763d',
    storageBucket: 'intromobile2-a763d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpyiQ53odeQjBsK5CK3aw-sV6Hci3Oa4I',
    appId: '1:1063136139964:ios:d5e1de49453185ca24ceb9',
    messagingSenderId: '1063136139964',
    projectId: 'intromobile2-a763d',
    storageBucket: 'intromobile2-a763d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationIntroMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpyiQ53odeQjBsK5CK3aw-sV6Hci3Oa4I',
    appId: '1:1063136139964:ios:d5e1de49453185ca24ceb9',
    messagingSenderId: '1063136139964',
    projectId: 'intromobile2-a763d',
    storageBucket: 'intromobile2-a763d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationIntroMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUV4A4ah7jkeQ5HPv7co16GL_2R0aKc9k',
    appId: '1:1063136139964:web:b5471ef45ac58ad524ceb9',
    messagingSenderId: '1063136139964',
    projectId: 'intromobile2-a763d',
    authDomain: 'intromobile2-a763d.firebaseapp.com',
    storageBucket: 'intromobile2-a763d.firebasestorage.app',
    measurementId: 'G-F9TH220140',
  );
}
